# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: 'bun'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '08:00'
    commit-message:
      prefix: 'deps'
      include: 'scope'
    versioning-strategy: widen
    open-pull-requests-limit: 5
