version: '3.8'

services:
  # Override to use production Docker image instead of building from source
  kratos-admin-ui:
    image: dhiagharsallaoui/kratos-admin-ui:latest
    build: null  # Remove build context
    volumes: []  # Remove development volume mounts
    environment:
      - NODE_ENV=production
      - KRATOS_ADMIN_URL=http://kratos:4434
      - KRATOS_PUBLIC_URL=http://kratos:4433
      # Remove NEXT_PUBLIC_ variables as they're not needed in production image