version: '3.8'

services:
  # Admin UI Service
  kratos-admin-ui:
    build:
      context: ..
      dockerfile: dev/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - KRATOS_ADMIN_URL=http://kratos:4434
      - KRATOS_PUBLIC_URL=http://kratos:4433
      - NEXT_PUBLIC_KRATOS_ADMIN_URL=http://localhost:4434
      - NEXT_PUBLIC_KRATOS_PUBLIC_URL=http://localhost:4433
    volumes:
      - ../:/app
      - /app/node_modules
    networks:
      - intranet
    depends_on:
      - kratos

  # Kratos Migration Service
  kratos-migrate:
    image: oryd/kratos:v1.3.1
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet

  # Kratos Main Service
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v1.3.1
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    networks:
      - intranet

  # Kratos Self-Service UI
  kratos-selfservice-ui:
    image: oryd/kratos-selfservice-ui-node:v1.3.1
    ports:
      - '4455:4455'
    environment:
      - PORT=4455
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
      - COOKIE_SECRET=changeme
      - CSRF_COOKIE_NAME=ory_csrf_ui
      - CSRF_COOKIE_SECRET=changeme
      - SECURITY_MODE=
    networks:
      - intranet
    restart: on-failure
    depends_on:
      - kratos

  # Mail Service for Testing
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet

  # Initialize test identities
  init-identities:
    image: curlimages/curl:latest
    depends_on:
      - kratos
    volumes:
      - type: bind
        source: ./init-identities.sh
        target: /init-identities.sh
    networks:
      - intranet
    command: sh /init-identities.sh
    restart: 'no'
    profiles:
      - init

networks:
  intranet:

volumes:
  kratos-sqlite:
