version: v1.3.1

dsn: sqlite:///var/lib/sqlite/db.sqlite?_fk=true

serve:
  public:
    base_url: https://kratos.ory.cloud-ctl.com/
    cors:
      enabled: true
      allowed_origins:
        - https://admin.ory.cloud-ctl.com
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Content-Type
        - X-Session-Token
      exposed_headers:
        - Content-Type
        - Set-Cookie
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: https://admin.ory.cloud-ctl.com/
  allowed_return_urls:
    - https://admin.ory.cloud-ctl.com
    - https://admin.ory.cloud-ctl.com/dashboard

  methods:
    password:
      enabled: true
    totp:
      config:
        issuer: Kratos Admin UI Demo
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true

  flows:
    error:
      ui_url: https://admin.ory.cloud-ctl.com/error

    settings:
      ui_url: https://admin.ory.cloud-ctl.com/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: https://admin.ory.cloud-ctl.com/recovery
      use: code

    verification:
      enabled: true
      ui_url: https://admin.ory.cloud-ctl.com/verification
      use: code
      after:
        default_browser_return_url: https://admin.ory.cloud-ctl.com/

    logout:
      after:
        default_browser_return_url: https://admin.ory.cloud-ctl.com/login

    login:
      ui_url: https://admin.ory.cloud-ctl.com/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: https://admin.ory.cloud-ctl.com/registration
      after:
        password:
          hooks:
            - hook: session

log:
  level: info
  format: json
  leak_sensitive_values: false

secrets:
  cookie:
    - abcdef1234567890abcdef1234567890
  cipher:
    - fedcba0987654321fedcba0987654321

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json
    - id: organizational
      url: file:///etc/config/kratos/company-identity.schema.json
    - id: customer
      url: file:///etc/config/kratos/customer.schema.json

courier:
  smtp:
    connection_uri: smtp://smtp:1025/?disable_starttls=true
